// Mocks generated by Mockito 5.4.2 from annotations
// in tdd/test/data/repositories/user_repositories_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:tdd/data/data.dart' as _i2;

import 'user_repositories_test.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeUserModel_0 extends _i1.SmartFake implements _i2.UserModel {
  _FakeUserModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [MockRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockMockRemoteDataSource extends _i1.Mock
    implements _i3.MockRemoteDataSource {
  MockMockRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.UserModel> userLogin({required _i2.UserModel? userModel}) =>
      (super.noSuchMethod(
        Invocation.method(
          #userLogin,
          [],
          {#userModel: userModel},
        ),
        returnValue: _i4.Future<_i2.UserModel>.value(_FakeUserModel_0(
          this,
          Invocation.method(
            #userLogin,
            [],
            {#userModel: userModel},
          ),
        )),
      ) as _i4.Future<_i2.UserModel>);
}
