# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Firebase testing"
  lane :upload_firebase do
    begin
      gradle(
        task: "assemble",
        build_type: 'Debug'
      )
      firebase_app_distribution(
        app: "1:297830272300:android:d885e35be589f8cf9e3089",
        firebase_cli_token: "1//0gj61n5BJAyHSCgYIARAAGBASNwF-L9IrR6reBa_CDKwGwMWysUXCGXpc4pXVvUCBmL3NdSd7gHD-yBZ-XDQLZOPUhtOTXLVB7Bg",
        release_notes: "RELEASE-NOTE",
        android_artifact_type: "APK",
        firebase_cli_path: "/usr/local/bin/firebase",
        apk_path: "../build/app/outputs/apk/release/app-release.apk"
      )
    end
  end
end
