name: learn-github-actions
on: 

push:

branches: 
- master

jobs: 
checks-bat-version

runs-on: ubuntu-latest

step: 
- uses: actions/checkout@v2
- uses: actions/setup-java@v2 #plugin setting for java

with:

distribution: "zulu"

java-version: "11" #defines java version

- uses: subosito/flutter-action@v2

with:

flutter-version: "3.10.1"

- run: flutter pub get #installing the plugins for the flutter project

- run: flutter test #running flutter test

- run: flutter build apk #building flutter apk

- run: flutter build appbundle #building flutter bundle


